"""Catálogo de páginas de origen que se rastrean.

Extraído del scraper para que añadir o quitar una lotería no obligue a tocar
la lógica. Cada entrada es la URL base; el scraper le añade «-AAAA-MM-DD».
"""

URLS_BASE: tuple[str, ...] = (
    "https://enloteria.com/resultados-anguilla-8am",
    "https://enloteria.com/resultados-anguilla-9am",
    "https://enloteria.com/resultados-anguilla-10am",
    "https://enloteria.com/resultados-anguilla-11am",
    "https://enloteria.com/resultados-anguilla-12pm",
    "https://enloteria.com/resultados-anguilla-1pm",
    "https://enloteria.com/resultados-anguilla-2pm",
    "https://enloteria.com/resultados-anguilla-3pm",
    "https://enloteria.com/resultados-anguilla-4pm",
    "https://enloteria.com/resultados-anguilla-5pm",
    "https://enloteria.com/resultados-anguilla-6pm",
    "https://enloteria.com/resultados-anguilla-7pm",
    "https://enloteria.com/resultados-anguilla-8pm",
    "https://enloteria.com/resultados-anguilla-9pm",
    "https://enloteria.com/resultados-anguilla-10pm",
    "https://enloteria.com/resultados-la-primera",
    "https://enloteria.com/resultados-la-primera-noche",
    "https://enloteria.com/resultados-lotedom",
    "https://enloteria.com/resultados-georgia-dia",
    "https://enloteria.com/resultados-georgia-tarde",
    "https://enloteria.com/resultados-georgia-noche",
    "https://enloteria.com/resultados-florida-tarde",
    "https://enloteria.com/resultados-florida-noche",
    "https://enloteria.com/resultados-new-york-tarde",
    "https://enloteria.com/resultados-new-york-noche",
    "https://enloteria.com/resultados-new-jersey-tarde",
    "https://enloteria.com/resultados-new-jersey-noche",
    "https://enloteria.com/resultados-la-suerte",
    "https://enloteria.com/resultados-la-suerte-6pm",
    "https://enloteria.com/resultados-king-lottery-dia",
    "https://enloteria.com/resultados-king-lottery-noche",
    "https://enloteria.com/resultados-real",
    "https://enloteria.com/resultados-real-noche",
    "https://enloteria.com/resultados-loteka",
    "https://enloteria.com/resultados-gana-mas",
    "https://enloteria.com/resultados-nacional-noche",
    "https://enloteria.com/resultados-haiti-bolet-9-30-am",
    "https://enloteria.com/resultados-haiti-bolet-10-30-am",
    "https://enloteria.com/resultados-haiti-bolet-11-30-am",
    "https://enloteria.com/resultados-haiti-bolet-5-30-pm",
    "https://enloteria.com/resultados-haiti-bolet-6-30-pm",
    "https://enloteria.com/resultados-haiti-bolet-7-30-pm",
    "https://enloteria.com/resultados-leidsa",
)
